/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uned.c00825.tarea2.gui;

import com.uned.c00825.tarea2.controllers.ProblemaController;
import com.uned.c00825.tarea2.da.ColaProblema;
import com.uned.c00825.tarea2.services.ProblemaService;
import com.uned.c00825.tarea2.validators.IncidenteValidator;
import com.uned.c00825.tarea2.validators.ProblemaValidator;

/**
 *
 * @author byron
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    private final ProblemaController problemaController;

    /**
     * Creates new form MenuPrincipal
     */
    public FrmMenuPrincipal(ProblemaController controller) {
        problemaController = controller;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnProblema = new javax.swing.JMenu();
        mnProblemaNuevo = new javax.swing.JMenuItem();
        mnProblemaTraslado = new javax.swing.JMenuItem();
        mnProblemaBorrar = new javax.swing.JMenuItem();
        mnIncidente = new javax.swing.JMenu();
        mnIncidenteNuevo = new javax.swing.JMenuItem();
        mnIncidenteBorrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tarea 2 Byron Roman");

        mnProblema.setText("Problemas");

        mnProblemaNuevo.setText("Nuevo");
        mnProblemaNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProblemaNuevoActionPerformed(evt);
            }
        });
        mnProblema.add(mnProblemaNuevo);

        mnProblemaTraslado.setText("Traslado de incidentes");
        mnProblemaTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProblemaTrasladoActionPerformed(evt);
            }
        });
        mnProblema.add(mnProblemaTraslado);

        mnProblemaBorrar.setText("Eliminar");
        mnProblemaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProblemaBorrarActionPerformed(evt);
            }
        });
        mnProblema.add(mnProblemaBorrar);

        jMenuBar1.add(mnProblema);

        mnIncidente.setText("Incidente");

        mnIncidenteNuevo.setText("Nuevo");
        mnIncidenteNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIncidenteNuevoActionPerformed(evt);
            }
        });
        mnIncidente.add(mnIncidenteNuevo);

        mnIncidenteBorrar.setText("Eliminar");
        mnIncidenteBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIncidenteBorrarActionPerformed(evt);
            }
        });
        mnIncidente.add(mnIncidenteBorrar);

        jMenuBar1.add(mnIncidente);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnProblemaNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProblemaNuevoActionPerformed
        (new FrmProblemaNuevo(problemaController)).setVisible(true);
    }//GEN-LAST:event_mnProblemaNuevoActionPerformed

    private void mnIncidenteNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIncidenteNuevoActionPerformed
       (new FrmIncidenteNuevo(problemaController)).setVisible(true);
    }//GEN-LAST:event_mnIncidenteNuevoActionPerformed

    private void mnIncidenteBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIncidenteBorrarActionPerformed
       (new FrmIncidenteBorrar(problemaController)).setVisible(true);
    }//GEN-LAST:event_mnIncidenteBorrarActionPerformed

    private void mnProblemaTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProblemaTrasladoActionPerformed
        (new FrmProblemaTraslado(problemaController)).setVisible(true);
    }//GEN-LAST:event_mnProblemaTrasladoActionPerformed

    private void mnProblemaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProblemaBorrarActionPerformed
          (new FrmProblemaBorrar(problemaController)).setVisible(true);
    }//GEN-LAST:event_mnProblemaBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal(
                        new ProblemaController(
                                new ProblemaService(
                                        new ColaProblema(), new ProblemaValidator(), new IncidenteValidator()
                                )
                        )
                ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnIncidente;
    private javax.swing.JMenuItem mnIncidenteBorrar;
    private javax.swing.JMenuItem mnIncidenteNuevo;
    private javax.swing.JMenu mnProblema;
    private javax.swing.JMenuItem mnProblemaBorrar;
    private javax.swing.JMenuItem mnProblemaNuevo;
    private javax.swing.JMenuItem mnProblemaTraslado;
    // End of variables declaration//GEN-END:variables
}
