/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uned.c00825.tarea2.gui;

import com.uned.c00825.tarea2.controllers.ProblemaController;
import com.uned.c00825.tarea2.entities.Problema;
import com.uned.c00825.tarea2.entities.ProblemaTableModel;
import com.uned.c00825.tarea2.validators.EntityValidationException;
import java.awt.CardLayout;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
 * @author byron
 */
public class FrmProblemaBorrar extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     *
     * @param controller
     */
    public FrmProblemaBorrar(ProblemaController controller) {
        problemaController = controller;
        initComponents();
        wizard = (CardLayout) pnlRoot.getLayout();
        setLocationRelativeTo(null);
        initTableModel(); // Aquí se inicializa el modelo de la tabla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlProblemas = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        spProblemasDestino = new javax.swing.JScrollPane();
        tblProblemasDestino = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminación de incidentes ");
        setMinimumSize(new java.awt.Dimension(670, 400));
        setPreferredSize(new java.awt.Dimension(670, 320));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        pnlRoot.setMinimumSize(new java.awt.Dimension(100, 400));
        pnlRoot.setPreferredSize(new java.awt.Dimension(640, 310));
        pnlRoot.setLayout(new java.awt.CardLayout());

        pnlProblemas.setMinimumSize(new java.awt.Dimension(635, 33));
        pnlProblemas.setPreferredSize(new java.awt.Dimension(635, 320));

        jPanel2.setMaximumSize(new java.awt.Dimension(800, 700));
        jPanel2.setPreferredSize(new java.awt.Dimension(620, 250));

        spProblemasDestino.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        spProblemasDestino.setMaximumSize(new java.awt.Dimension(610, 100));
        spProblemasDestino.setName(""); // NOI18N
        spProblemasDestino.setPreferredSize(new java.awt.Dimension(610, 402));

        tblProblemasDestino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProblemasDestino.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblProblemasDestino.setFillsViewportHeight(true);
        tblProblemasDestino.setRowSorter(null);
        tblProblemasDestino.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblProblemasDestino.setShowGrid(true);
        spProblemasDestino.setViewportView(tblProblemasDestino);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(spProblemasDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(spProblemasDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlProblemas.add(jPanel2);

        btnEliminar.setText("Borrar");
        btnEliminar.setName("btnEliminar"); // NOI18N
        btnEliminar.setPreferredSize(new java.awt.Dimension(130, 23));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlProblemas.add(btnEliminar);

        pnlRoot.add(pnlProblemas, "card2");

        getContentPane().add(pnlRoot);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        borrarProblema();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * Método que simula el binding entre la interfaz y el modelo. Lee los datos
     * de los componentes, crea un objeto Problema y lo envía al controlador.
     */
    private void borrarProblema() {
        try {
            Problema frente = problemaController.peek();
            if (frente != null) {
                if (frente.getIncidents().isEmpty()) {
                    problemaController.dequeue();
                } else {
                    JOptionPane.showMessageDialog(this, "El problema tiene incidentes asociados, por lo que no se puede eliminar",
                            "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this, "No hay problemas",
                        "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }
            initTableModel();

        } catch (EntityValidationException ex) {
            // Para notificar errores se utiliza un cuadro de diálogo; según el enunciado, se debe limitar su uso a excepciones.
            JOptionPane.showMessageDialog(this, "Validaciones no superadas: " + ex.getValidationResult()
                    .getErrors()
                    .stream()
                    .map(e -> e.getMessage())
                    .collect(Collectors.joining("\n\t")),
                    "Atención", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            // Para notificar errores se utiliza un cuadro de diálogo; según el enunciado, se debe limitar su uso a excepciones.
            JOptionPane.showMessageDialog(this, "Error al registrar el problema: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void initTableModel() {
        // Definimos las columnas según los datos que queremos mostrar
        destinationTableModel = new ProblemaTableModel(problemaController.getAll());
        // Asignamos el modelo a la tabla
        tblProblemasDestino.setModel(destinationTableModel);
        tblProblemasDestino.updateUI();
    }
    private ProblemaTableModel destinationTableModel;
    private ProblemaController problemaController;

    private CardLayout wizard;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlProblemas;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JScrollPane spProblemasDestino;
    private javax.swing.JTable tblProblemasDestino;
    // End of variables declaration//GEN-END:variables
}
