/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uned.c00825.tarea2.gui;

import com.uned.c00825.tarea2.controllers.ProblemaController;
import com.uned.c00825.tarea2.entities.Problema;
import com.uned.c00825.tarea2.entities.ProblemaTableModel;
import com.uned.c00825.tarea2.validators.EntityValidationException;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
 * @author byron
 */
public class FrmProblemaNuevo extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     * @param controller
     */
    public FrmProblemaNuevo(ProblemaController controller) {
        problemaController = controller;
         initComponents();
        setLocationRelativeTo(null);
        initTableModel(); // Aquí se inicializa el modelo de la tabla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        spProblemas = new javax.swing.JScrollPane();
        tblProblemas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de problemas");
        setPreferredSize(new java.awt.Dimension(650, 220));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblId.setText("Id : ");
        lblId.setName("lblId"); // NOI18N
        lblId.setPreferredSize(new java.awt.Dimension(120, 16));
        getContentPane().add(lblId);

        txtId.setEditable(false);
        txtId.setEnabled(false);
        txtId.setFocusable(false);
        txtId.setPreferredSize(new java.awt.Dimension(100, 22));
        getContentPane().add(txtId);

        jLabel1.setEnabled(false);
        jLabel1.setFocusable(false);
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 16));
        getContentPane().add(jLabel1);

        lblDescription.setText("Descripción : ");
        lblDescription.setName("lblFecha"); // NOI18N
        lblDescription.setPreferredSize(new java.awt.Dimension(120, 16));
        getContentPane().add(lblDescription);
        lblDescription.getAccessibleContext().setAccessibleName("Descripción : ");

        txtDescription.setPreferredSize(new java.awt.Dimension(350, 30));
        getContentPane().add(txtDescription);

        btnRegistrar.setText("Registrar");
        btnRegistrar.setName("btnRegistrar"); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);

        spProblemas.setMaximumSize(new java.awt.Dimension(1000, 100));
        spProblemas.setName(""); // NOI18N
        spProblemas.setPreferredSize(new java.awt.Dimension(800, 402));

        tblProblemas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProblemas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblProblemas.setFillsViewportHeight(true);
        tblProblemas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblProblemas.setShowGrid(true);
        spProblemas.setViewportView(tblProblemas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(spProblemas, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(spProblemas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        getAccessibleContext().setAccessibleName("Registro de problemas");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrarProblema();
    }//GEN-LAST:event_btnRegistrarActionPerformed
    

    /**
     * Método que simula el binding entre la interfaz y el modelo. Lee los datos
     * de los componentes, crea un objeto Problema y lo envía al controlador.
     */
    private void registrarProblema() {
        try {
            String descripcion = txtDescription.getText();             

            Problema problema = new Problema(descripcion);
            problemaController.register(problema);
            tableModel.addRow(problema);
            txtDescription.setText("");            
            tblProblemas.updateUI();

        } catch (EntityValidationException ex) {
            // Para notificar errores se utiliza un cuadro de diálogo; según el enunciado, se debe limitar su uso a excepciones.
            JOptionPane.showMessageDialog(this, "Validaciones no superadas: " + ex.getValidationResult()
                    .getErrors()
                    .stream()
                    .map(e -> e.getMessage())
                    .collect(Collectors.joining("\n\t")),
                     "Atención", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            // Para notificar errores se utiliza un cuadro de diálogo; según el enunciado, se debe limitar su uso a excepciones.
            JOptionPane.showMessageDialog(this, "Error al registrar el problema: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    private void initTableModel() {

        // Definimos las columnas según los datos que queremos mostrar
        tableModel = new ProblemaTableModel(problemaController.getAll());

        // Asignamos el modelo a la tabla
        tblProblemas.setModel(tableModel);
        
    }
    
    private ProblemaTableModel tableModel;
    private ProblemaController problemaController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblId;
    private javax.swing.JScrollPane spProblemas;
    private javax.swing.JTable tblProblemas;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
